import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Meu projeto em Next",
  description: "Generated by create next app",
};

//Aula 5 - Layoult 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <h1>Layout da Pagina (Header)</h1>

        {children}

        {/*Aula 6 - Componentes no next*/}
           <Footer />

      </body>
    </html>
  );
}
